//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mkh.Tools.CLI.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mkh.Tools.CLI.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 快去用代码改变世界吧~ 的本地化字符串。
        /// </summary>
        internal static string ChangeTheWord {
            get {
                return ResourceManager.GetString("ChangeTheWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [red]代码目录 [yellow]{0[/] 已存在，请手动移除后再创建。[/] 的本地化字符串。
        /// </summary>
        internal static string CodeDirIsExists {
            get {
                return ResourceManager.GetString("CodeDirIsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建模块 的本地化字符串。
        /// </summary>
        internal static string CreateModule {
            get {
                return ResourceManager.GetString("CreateModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块创建成功 的本地化字符串。
        /// </summary>
        internal static string CreateModuleSuccess {
            get {
                return ResourceManager.GetString("CreateModuleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 17MKH 脚手架 的本地化字符串。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取最新的PM依赖包版本号 的本地化字符串。
        /// </summary>
        internal static string GetLatestNpmVersion {
            get {
                return ResourceManager.GetString("GetLatestNpmVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取最新NuGet依赖包版本号 的本地化字符串。
        /// </summary>
        internal static string GetLatestNuGetVersion {
            get {
                return ResourceManager.GetString("GetLatestNuGetVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块编号不能大于55000 的本地化字符串。
        /// </summary>
        internal static string ModuleNoCantGreaterThan {
            get {
                return ResourceManager.GetString("ModuleNoCantGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块编号不能小于0 的本地化字符串。
        /// </summary>
        internal static string ModuleNoCantLessThan {
            get {
                return ResourceManager.GetString("ModuleNoCantLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建模块、皮肤 的本地化字符串。
        /// </summary>
        internal static string NewCommandDescription {
            get {
                return ResourceManager.GetString("NewCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建皮肤 的本地化字符串。
        /// </summary>
        internal static string NewSkinCommandDescription {
            get {
                return ResourceManager.GetString("NewSkinCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入您的公司单位 的本地化字符串。
        /// </summary>
        internal static string PleaseInputCompany {
            get {
                return ResourceManager.GetString("PleaseInputCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入您的版权声明 的本地化字符串。
        /// </summary>
        internal static string PleaseInputCopyright {
            get {
                return ResourceManager.GetString("PleaseInputCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入模块编码[red](必填)[/] 的本地化字符串。
        /// </summary>
        internal static string PleaseInputModuleCode {
            get {
                return ResourceManager.GetString("PleaseInputModuleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入模块图标 的本地化字符串。
        /// </summary>
        internal static string PleaseInputModuleIcon {
            get {
                return ResourceManager.GetString("PleaseInputModuleIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入模块名称[red](必填)[/] 的本地化字符串。
        /// </summary>
        internal static string PleaseInputModuleName {
            get {
                return ResourceManager.GetString("PleaseInputModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入模块编号(0-55000)[red](必填)[/] 的本地化字符串。
        /// </summary>
        internal static string PleaseInputModuleNo {
            get {
                return ResourceManager.GetString("PleaseInputModuleNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入模块备注 的本地化字符串。
        /// </summary>
        internal static string PleaseInputModuleRemarks {
            get {
                return ResourceManager.GetString("PleaseInputModuleRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似     欢迎使用 [{0}]17MKH[/] 快速开发框架 的本地化字符串。
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
