//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mkh.Tools.CLI.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language_enUS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_enUS() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mkh.Tools.CLI.Resources.Language.enUS", typeof(Language_enUS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Go change the world with code~ 的本地化字符串。
        /// </summary>
        internal static string ChangeTheWord {
            get {
                return ResourceManager.GetString("ChangeTheWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [red] The code save directory  [yellow]{0[/] is exists,Please manually remove it and create it again.[/] 的本地化字符串。
        /// </summary>
        internal static string CodeDirIsExists {
            get {
                return ResourceManager.GetString("CodeDirIsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Module 的本地化字符串。
        /// </summary>
        internal static string CreateModule {
            get {
                return ResourceManager.GetString("CreateModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Module created successfully 的本地化字符串。
        /// </summary>
        internal static string CreateModuleSuccess {
            get {
                return ResourceManager.GetString("CreateModuleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 17MKH CLI 的本地化字符串。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get the latest NPM dependency package version number 的本地化字符串。
        /// </summary>
        internal static string GetLatestNpmVersion {
            get {
                return ResourceManager.GetString("GetLatestNpmVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get the latest NuGet dependency package version number 的本地化字符串。
        /// </summary>
        internal static string GetLatestNuGetVersion {
            get {
                return ResourceManager.GetString("GetLatestNuGetVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The module number cannot be larger than 55000 的本地化字符串。
        /// </summary>
        internal static string ModuleNoCantGreaterThan {
            get {
                return ResourceManager.GetString("ModuleNoCantGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The module number must be greater than or equal to 0 的本地化字符串。
        /// </summary>
        internal static string ModuleNoCantLessThan {
            get {
                return ResourceManager.GetString("ModuleNoCantLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Module、Skin 的本地化字符串。
        /// </summary>
        internal static string NewCommandDescription {
            get {
                return ResourceManager.GetString("NewCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Skin 的本地化字符串。
        /// </summary>
        internal static string NewSkinCommandDescription {
            get {
                return ResourceManager.GetString("NewSkinCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter your company 的本地化字符串。
        /// </summary>
        internal static string PleaseInputCompany {
            get {
                return ResourceManager.GetString("PleaseInputCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter your copyright 的本地化字符串。
        /// </summary>
        internal static string PleaseInputCopyright {
            get {
                return ResourceManager.GetString("PleaseInputCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a module code[red](Required)[/] 的本地化字符串。
        /// </summary>
        internal static string PleaseInputModuleCode {
            get {
                return ResourceManager.GetString("PleaseInputModuleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a module icon 的本地化字符串。
        /// </summary>
        internal static string PleaseInputModuleIcon {
            get {
                return ResourceManager.GetString("PleaseInputModuleIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a module name[red](Required)[/] 的本地化字符串。
        /// </summary>
        internal static string PleaseInputModuleName {
            get {
                return ResourceManager.GetString("PleaseInputModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a module number(0-55000)[red](Required)[/] 的本地化字符串。
        /// </summary>
        internal static string PleaseInputModuleNo {
            get {
                return ResourceManager.GetString("PleaseInputModuleNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a module remarks 的本地化字符串。
        /// </summary>
        internal static string PleaseInputModuleRemarks {
            get {
                return ResourceManager.GetString("PleaseInputModuleRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome to use [{0}]17MKH[/] rapid development framework 的本地化字符串。
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
